server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus?serverTimezone=UTC
    username: root
    password: admin
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
